### ISSUE TITLE
Convert Module Name to NetworkingDsc

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/NetworkingDsc#290]
As per recent DSC Resource Naming guidelines changes:
https://github.com/PowerShell/DscResources/blob/master/Naming.md

**Comment by rchaganti** [comment]
I just started NetworkingDsc in my account. I have a new resource that I needed and thought why not start making it as a HQRM. You can check it at https://github.com/rchaganti/NetworkingDsc.

**Comment by PlagueHO** [comment]
Hi @rchaganti - great stuff! Are you planning on merging your NetworkingDsc in with this repo once we've completed the rename?

**Comment by rchaganti** [comment]
Yes. Do you have any timelines?

**Comment by PlagueHO** [comment]
I wanted to complete #135 before converting to NetworkingDsc, but I think this will take at least a few weeks if I do one resource every couple of days (takes a little bit of time for reviews to go through). But there isn't strictly any reason why I need to complete the HQRM work before renaming this module.

I'd love to have this complete before next resource kit release (end of Jan?) - so would that timeline work for you?

**Comment by rchaganti** [comment]
Yes, that will work. I will start adding tests to my resource. Is there any new resource backlog that you are tracking? I can help write some after holidays.

**Comment by PlagueHO** [comment]
Hi @rchaganti - sorry it took so long, but we've now completed the rename of xNetworking to NetworkingDsc. So if the offer of including your resources is still available then they'd be gratefully accepted!
