### ISSUE TITLE
xNetworkTeam: LACP handshake delay ignored?

### ISSUE THREAD

**Issue by error53** [PowerShell/NetworkingDsc#319]
I'm using xNetworking 5.5.0.0 to build a NIC team on a Win2016 server:

ConfigurationMode              : ApplyAndAutoCorrect
ConfigurationModeFrequencyMins : 30

`
<snip>
  		xNetworkTeam NICTeam {
			Name                   = 'TEAM01'
			TeamingMode            = 'LACP'
			LoadBalancingAlgorithm = 'Dynamic'
			TeamMembers            = 'NIC-1', 'NIC-2'
			Ensure                 = 'Present'
		}
		xDhcpClient DisableDhcpClient {
			State          = 'Disabled'
			InterfaceAlias = 'TEAM01'
			AddressFamily  = 'IPv4'
			DependsOn      = '[xNetworkTeam]NICTeam'
		}
		xIPAddress IPv4Address {
			IPAddress      = "$IPaddress/24"
			InterfaceAlias = 'TEAM01'
			AddressFamily  = 'IPv4'
			DependsOn      = '[xDhcpClient]DisableDhcpClient'
		}
		xDefaultGatewayAddress SetDefaultGateway {
			Address        = "$($GWaddress)"
			InterfaceAlias = 'TEAM01'
			AddressFamily  = 'IPv4'
			DependsOn      = '[xIPAddress]IPv4Address'
		}
<snap>
`

the initial run of Start-DSCConfiguration fails to configure the IP address and/or the default gateway. But when I walk away and check again next morning, all my resources report "InDesiredState"

BUT: when I watch the verbose output of Start-DSCConfiguration, the above steps complete within seconds. When I configure this manually, my LACP team needs 1-2 minutes to complete the LACP handshake and to come online.

I have not found a "DSC delay" resource yet or I would insert that between NICTeam" and "DisableDhcpClient" to verify my guesstimated timing problem here. running Start-DSCConfiguration twice does not help. running Start-DSCConfiguration again 10 minutes later seems to work.

any chance that this is a bug ignoring the team status and continuing too fast? or just a noob error with the configuration above??

other ideas and/or suggestions ?

thanks in advance

**Comment by error53** [comment]
sorry about the ugly "code" above. how to I keep the line breaks in there?

**Comment by PlagueHO** [comment]
Hi @error53 - thanks for submitting this. You can keep formatting by using three backticks on a single line (optionally followed by a language that the code block contains) to start a code block and then end it with three back ticks. E.g.
```powershell
xNetworkTeam NICTeam {
    Name = 'TEAM01'
    TeamingMode = 'LACP'
    LoadBalancingAlgorithm = 'Dynamic'
   TeamMembers = 'NIC-1', 'NIC-2'
   Ensure = 'Present'
}
xDhcpClient DisableDhcpClient {
   State = 'Disabled'
   InterfaceAlias = 'TEAM01'
   AddressFamily = 'IPv4'
   DependsOn = '[xNetworkTeam]NICTeam'
}
xIPAddress IPv4Address {
    IPAddress = "$IPaddress/24"
    InterfaceAlias = 'TEAM01'
    AddressFamily = 'IPv4'
    DependsOn = '[xDhcpClient]DisableDhcpClient'
}
xDefaultGatewayAddress SetDefaultGateway {
    Address = "$($GWaddress)"
    InterfaceAlias = 'TEAM01'
    AddressFamily = 'IPv4'
    DependsOn = '[xIPAddress]IPv4Address'
}
```

But there is a known issue where after creating the team it isn't ready for a little while (10-60 seconds). In fact we actually have to put a delay into our integration tests to handle this (https://github.com/PowerShell/xNetworking/blob/dev/Tests/Integration/MSFT_xNetworkTeamInterface.Integration.Tests.ps1#L74).

I think the solution to this is for us to create a new resource called xWaitForNetworkTeam that will wait for the team to report that it is ready before continuing. This is a pattern that has been used in other resources (xWaitForDisk etc.)

What do you think - would that address your issue?

**Comment by error53** [comment]
I guess it's awfully hard to predict the LACP handshake delay until a multi-NIC team becomes active? but such a xWaitForNetworkTeam resource sounds just like what I need to handle my problem.

thanks a lot

**Comment by PlagueHO** [comment]
@error53 - sorry this took so long, but I'm now submitting the new resource for review.
