### ISSUE TITLE
NetworkingDsc missing in PSGallery

### ISSUE THREAD

**Issue by krishdevan** [PowerShell/NetworkingDsc#332]
I tried to download the resource today and I got a message that there was no match found on 'NetworkingDSC' is PSGallery :(

**Comment by PlagueHO** [comment]
Hi There @krishdevan - this should be released to the PSGallery in the next monthly Resource Kit release (in a couple of weeks I think). I'll hold this open until then.

**Comment by johlju** [comment]
Next Community Call is on June 6:th, the release is usually a week after that, so mid June.

**Comment by easyveazie** [comment]
Still seeing this today. Is there a place to see when the schedule releases are?

`PS C:\Projects> Find-Module -Name NetworkingDsc -Repository PSGallery | Install-Module
PackageManagement\Find-Package : No match was found for the specified search criteria and module name 'NetworkingDsc'.
Try Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1397 char:3
+         PackageManagement\Find-Package @PSBoundParameters | Microsoft ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...ets.FindPackage:FindPackage) [Find-Package], Exceptio
   n
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.FindPackage`

**Comment by johlju** [comment]
Next release should be soon, maybe tomorrow, but definitely this week (unless I missed something). You can see it being released when there is a release PR being merged.

**Comment by PlagueHO** [comment]
Closing now as this has been released to PSGallery: https://www.powershellgallery.com/packages/NetworkingDsc
