### ISSUE TITLE
Set-NetIPInterface -Forwarding Enabled

### ISSUE THREAD

**Issue by codykonior** [PowerShell/NetworkingDsc#355]
This command is often used in lab setups to enable forwarding between NICs without setting up routing infrastructure.

But I don't see anything in this resource module which allows that. Have I missed it?

**Comment by PlagueHO** [comment]
Hi There @codykonior - we haven't added a resource to expose this function. This could probably be exposed (along with other interface type settings) fairly easily.

**Comment by PlagueHO** [comment]
I'm working on adding this as a resource now (along with some additional settings).

We actually have other resources that use this cmdlet to perform other specific tasks, but for some reason the specific functionality is separated (WeakHostRecieve and WeakHostSend). It would have made more sense to combine all this into a single resource (NetInterface).

I'll probably create the NetInterface resource and just put into the README.MD that the specific settings WeakHostRecieve and WeakHostSend are in separate resources. At some point in the future it might be worth looking at deprecating the WeakHost* resources in favor of the more generic NetInterface.
