### ISSUE TITLE
Firewall: Would like it to support enabling a group instead of rule

### ISSUE THREAD

**Issue by codykonior** [PowerShell/NetworkingDsc#356]
#### Details of the scenario you tried and the problem that is occurring
I want to enable File and Printer Sharing firewall rules on a server. 

Doing that in cmd or PowerShell are trivial:

```
& netsh advfirewall firewall set rule group="File and Printer Sharing" new enable=Yes
Get-NetFirewallRule -DisplayGroup 'File and Printer Sharing' | Set-NetFirewallRule -Enabled True
```

However the Firewall resource does not allow you to enable an entire group of rules, only rule by rule. This is complex to maintain especially as the rules could conceivably be different from version to version of the OS.

So I'd like an enhancement that allows enabling/disabling an entire group. However, looking at the code, this doesn't appear to be easy.

#### Suggested solution to the issue
I'm not so sure it's possible to use the existing resource because the Name property is mandatory and tightly integrated with the code. Even if you allowed a * or All it would require a lot of changes.

But ideally it that wasn't the case it would look like this:

```
Configuration Example
{
    param
    (
        [Parameter()]
        [System.String[]]
        $NodeName = 'localhost'
    )

    Import-DSCResource -ModuleName NetworkingDsc

    Node $NodeName
    {
        Firewall Firewall
        {
	    Group = 'File and Printer Sharing'
            Ensure                = 'Present'
            Enabled               = 'True'
        }
    }
}
```

**Comment by PlagueHO** [comment]
Hi @codykonior - this is a good question/proposal. It sounds like a really reasonable use case. However, there are some challenges with it:

1. It could lead to configs that can never go into state.
2. The key for the resource is the firewall rule name (as opposed to the group). Changing the key pretty much isn't an option for this resource.

However, one possible solution to 2 is to create a new resource `FirewallGroup` that could be used for this purpose. Something like this:
```powershell
Configuration Example
{
    Import-DSCResource -ModuleName NetworkingDsc

    Node localhost
    {
        FirewallGroup EnableFileAndPrinterSharing
        {
	    Group = 'File and Printer Sharing'
            Enabled = 'True'
        }
    }
}
```

The big risk though in using this is item 1 above - it could easily be combined with the Firewall resource to produce a config that internally conflicts and can't go into state. For example:
```powershell
Configuration Example
{
    Import-DSCResource -ModuleName NetworkingDsc

    Node localhost
    {
        FirewallGroup EnableFileAndPrinterSharing
        {
	    Group = 'File and Printer Sharing'
            Enabled = 'True'
        }

        Firewall DisableFileAndPrinterSharingSpooler
        {
            Name = 'File and Printer Sharing (Spooler Service - RPC-EPMAP)'
            Enabled = 'False'
        }
    }
}
```

The above config would continue to reapply over and over without ever going into state. This is fairly obvious example and in most cases common sense and testing would easily avoid this problem, but it is worth pointing out.

Perhaps just providing a summary of the risk in the README.MD for the resource would be adequate. @johlju - any thoughts?

**Comment by johlju** [comment]
I agree with @PlagueHO that creating a FirewallGroup resource could potentially result in that the target node never will get to a desired state if used together with Firewall resource, especially when using partial configurations.
On the other hand I see the problem getting all the rules for a specific group to be able to get all into the configuration.

One thing that comes to mind is to instead create FirewallSet composite resource (it could be called FirewallGroup too), like ServiceSet. FirewallSet would build an array of Firewall resources at compile time. The problem is that it need to be compiled on same same Windows edition and version as it is gonna be run on, otherwise the mof file could potentially miss some rules in the group. 🤔 
See: https://github.com/PowerShell/xPSDesiredStateConfiguration/tree/dev/DSCResources/xServiceSet

Another variant is a helper function that takes a group name, then builds a configuration script using a bunch of Firewall resources that can be used by the user in their final configuration.

**Comment by codykonior** [comment]
I won't be able to use a version that only creates a MOF based on rules that exist on the host rather than the guest.

I don't see the problem with having a DSC rule that may never resolve IF YOU WRITE IT INCORRECTLY. This pretty much describes every DSC resource ever.

**Comment by johlju** [comment]
Another option is that Name takes a predefined format to determine that it is a group name, like `Name = 'FirewallGroup:File and Printer Sharing`. Aa keyword that is unique and can be parsed easily by regular expression. 🤔 

> I won't be able to use a version that only creates a MOF based on rules that exist on the host rather than the guest

That is the downside using the FirewallSet-alternative.

> The argument that it may not resolve does not hold water when you can do the exact same thing with the existing resource and any other DSC resource that exists.

Not following you here. If you mean my phrase "miss some rules in the group". I mean that on WIndows Server 2019 there might be one more rule (or one less rule) than on Windows Server 2016. So both my previous alternative are not good. 🙂
