### ISSUE TITLE
Exclusive Firewall Rule Definitions

### ISSUE THREAD

**Issue by merddyin** [PowerShell/NetworkingDsc#359]
### Description
Firewall enforcement resource. I've seen another posting on here regarding trying to exclude only custom defined rules, but what I'm suggesting is far more basic...my rules only. 

### Proposed properties
Two properties; Enforcement = Absent/Present, and ReportOnly Absent/Present

### Special considerations or limitations
The general idea is that anything not defined within the config is considered out of compliance. With both Enforcement and ReportOnly set to Present (or some other positive indicator), DSC would report all enabled firewall rules not defined in the config as drift, but would otherwise do nothing. This provides a mechanism to test config without breaking things, or identify which other rules you might need to add to the config, or even just to report on deviations from a company standard.

With ReportOnly set to Absent (or some other negative indicator), but Enforcement set to Enabled, any rules not defined in the config would be forcefully disabled. I thought about having them get deleted, but it would be hard to manage that, particularly with things getting installed and creating new rules. 

I'm not entirely sure how this could be pulled off, but (at least in my oddly wired brain) I'm thinking it should be possible to basically write out any non-defined rules as a new partial DSC config, then self-applying the partial config to itself before deleting the temp files. Not sure that's even possible. The only issue is that this wouldn't allow for the ReportOnly functionality as I'm not aware of any way to only enforce parts of a config, or have different policies for different partials. The key piece is not having the firewall rules that need to be dynamically disabled written anywhere directly accessible to the admins of the box, which is why I think config. I realize that GPO is better suited to this type of enforcement, but it lacks granular definition without a substantial amount of overhead, whereas DSC is easier to target by system. This sort of functionality should be useful across any number of other modules as well I would think.

**Comment by PlagueHO** [comment]
This is an interesting proposal that definitely deserves some more thought and consideration. It is one of the more challenging (and very long running) problems we've tried and failed to solve.

Are you able to add an example config of what you'd expect to provide (with the ReportOnly and Enforcement) as well as the behavior you'd expect to see with the combination?
