### ISSUE TITLE
Discussion: Deprecate WeakHostSend, WeakHostRecieve and DHCPClient

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/NetworkingDsc#360]
The `WeakHostSend`, `WeakHostRecieve` and `DHCPClient` resources all configure properties on the `*-NetIPInterface`. They are "single purpose" resources that result in a lot of duplicated code/function. E.g. the resources are practically identical (duplicated code, tests etc).

I'm currently implementing a more generic `NetIPInterface` resource that can be used to configure properties on the `*-NetIPInterface` as part of #355. I'm excluding the `WeakHostSend`, `WeakHostRecieve` and `DHCPClient` properties as they are covered by these other resources.

But it seems to me to be non-trivial duplication of function/tests. This would reduce the amount of code and tests needing to be maintained and also simplify configurations - but of course would be a BREAKING CHANGE.

For example, the following current config:
```powershell
Configuration Example
{
    Import-DscResource -Module NetworkingDsc

    Node localhost
    {
        DhcpClient EnableDhcpClient
        {
            InterfaceAlias = 'Ethernet'
            AddressFamily  = 'IPv4'
            State          = 'Enabled'
        }

        WeakHostSend DisableWeakHostReceiving
        {
            InterfaceAlias = 'Ethernet'
            AddressFamily  = 'IPv4'
            State          = 'Disabled'
        }

        WeakHostSend DisableWeakHostSending
        {
            InterfaceAlias = 'Ethernet'
            AddressFamily  = 'IPv4'
            State          = 'Disabled'
        }
    }
}
```

Would be changed to:
```powershell
Configuration Example
{
    Import-DscResource -Module NetworkingDsc

    Node localhost
    {
        NetIPInterface ConfigureNetIPInterface
        {
            InterfaceAlias = 'Ethernet'
            AddressFamily  = 'IPv4'
            DHCP          = 'Enabled'
            WeakHostSend = 'Disabled'
            WeakHostRecieve = 'Disabled'
        }
    }
}
```

@tysonjhayes , @johlju - what are your thoughts on this?

**Comment by johlju** [comment]
I suggest deprecate the resource, merging them into the new resource - and in a later PR (maybe when doing another breaking change) remove them. 
We had a similar scenario in SqlServerDsc a while back - I waited a couple of released, then I removed them as a breaking change.

**Comment by PlagueHO** [comment]
Cool. That what I was thinking.

**Comment by PlagueHO** [comment]
Bumping to keep this open for now.

**Comment by PlagueHO** [comment]
I will plan to implement this change over the next few weeks.
