### ISSUE TITLE
Net* for all interfaces

### ISSUE THREAD

**Issue by technion** [PowerShell/NetworkingDsc#362]
### Description
Hi,
I'm specifically interested in the NetBIOS module, but most of the Net* modules appear to have the same difficulty.

It's quite difficult to deploy to a group of servers as it requires an interface name which isn't always consistent. There's a variety of reasons for that, the recent Windows Update issues meaning a lot of servers only have "Ethernet 2" is one. Hyper-V hosts have names that refer to switches for example, and many servers just have several NICs.

As an aside, for the purposes these modules fill, I'd imagine more people are interested in building DSC rules for all interfaces than specifying one.

### Proposed properties
These modules should allow an "all interfaces" option. An example would be for this to be the default if no interface was named.

**Comment by PlagueHO** [comment]
Hi @technion - have you looked at using the NetAdapterName resource to force an adapter (based on driver or MAC address or Guid or whatever) to be set to a specific name? If you configure the network adapter name to an expected name first in your config then all other network resources can be used to refer to a specific adapter.

Failing that, it would be possible to allow an "all interfaces" option on _some_ resources. Obviously, some resources it wouldn't make sense to allow this. There would need to be additional investigation on this as this wouldn't be a trivial amount of work.

**Comment by technion** [comment]
@PlagueHO Thanks for that advice. I've looked across NetAdapterName but as far as I can see I'd still need something consistent to start with. For example, my colleague has one NetAdapter. My machine has:

- Ethernet - physical
- Ethernet 2 - TAP adapter
- vEthernet - Hyper-V

I'm not sure how I'd write one DSC for all cases.

I'd really like to see Microsoft introduce a reg key that would just disable NetBIOS everywhere, but in the absence of that, I'm hoping there's an option here. I do appreciate feature requests can be painful if only person asks.

**Comment by PlagueHO** [comment]
Ah right - I didn't notice that you requested this specifically for the NetBIOS resources (I thought "all" Net resources). So this is a much more "doable" request :grin: At the moment we don't have too many contributors (and reviewers) to the Networking module so it is mainly down to when I (or someone else) gets time to do it. I'll try and look into it over the next week or so though.

**Comment by nmdange2** [comment]
@technion See this page which explains how you can provide environment data to your DSC.  In your config file, you would specify the NIC name for each system
https://docs.microsoft.com/en-us/powershell/dsc/separatingenvdata

**Comment by PlagueHO** [comment]
This has now been completed in this PR - https://github.com/PowerShell/NetworkingDsc/pull/414
