### ISSUE TITLE
Possibility to enable a Network Adapter

### ISSUE THREAD

**Issue by Big--Mike** [PowerShell/NetworkingDsc#365]
I searched through the resources and ended up writing a small script resource to ensure, because I didn't find what I was looking for.
I'd like to ensure, that a network adapter is enabled, but it seems, that there's no fitting resource?

**Comment by Big--Mike** [comment]
Basically, I like to ensure network connections on some machines, which are used for test scenarios, and therefore also by users with admin privileges, are pretty robust against configuration failures, such that a user which locks himself out from the machine by killing the network or RDP access needs only to wait, until LCM repairs it all. 
If this fails, the user has to open a support ticket, because they have no access to the underlying virtualization environment and therefore, no console access. Which means more work and more waiting.
As the machines have multiple network adapters and network loss is simulated by disabling the network adapter, I'd like to ensure, that the one for the RDP connection of the tester gets enabled again, if it's diabled by accident. (That really happened before)

If you don't see a need, I can live with my solution with the script resource.

**Comment by rdavisunr** [comment]
Came here looking for this resource too! Looks like it's getting close; any idea on release timing?

**Comment by PlagueHO** [comment]
Sorry @rdavisunr - thank you for reminding me. Too many jobs on the go. I'll aim to get this sorted this weekend once @danielboth has resolved the conflicts. I dropped the ball. Sorry about that!
