### ISSUE TITLE
Include "MaxRxRing1Length" and "NumRxBuffersSmall" in the xNetAdapterAdvancedProperty validate set

### ISSUE THREAD

**Issue by AussieDavo** [PowerShell/NetworkingDsc#387]
Hi @PlagueHO would it be possible to also include "MaxRxRing1Length" and "NumRxBuffersSmall" in the xNetAdapterAdvancedProperty validate set.

**Comment by PlagueHO** [comment]
Hi @AussieDavo - yep. I reckon this should be reasonably easy to action. If someone else doesnt pick it up I will.

**Comment by AussieDavo** [comment]
Thanks @PlagueHO . Any idea when this will be released into the master build?

**Comment by PlagueHO** [comment]
Hi @AussieDavo , it is usually released about a week after the DSC Resource kit community call, which is happening tomorrow. So it will be in about 8 days, give or take.
