### ISSUE TITLE
Discussion: NetAdapterAdvancedProperty remove ValidateSet from RegistryKeyword

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/NetworkingDsc#388]
This is a request for discussion.

Currently the RegistryKeyword in NetAdapterAdvancedProperty is validated against a long set of valid RegistryKeywords. This is helpful for users to ensure they set the correct Registry Keywords.

However, it requires a change to the resource every time new valid values need to be added. This doesn't happen often (twice times in 18 months). But it is possible that other users have needed additional entries and either modified the resource or not used it at all.

I don't think this is a major issue as adding new entries is trivial. The problem though is that it isn't possible to validate the entry and the entries that are available on an adapter will depend on the network adapter driver provider.

**Comment by dcuomo** [comment]
Hi @PlagueHO - I'm the PM owner for the server data plane and basically all of the Advanced Registry 
 Keywords.  

I agree with you that the validation is unnecessary.  There are currently non-standard registry keywords included in the resource (e.g. those without the asterisk in front).  These are implemented by the specific NIC vendor and could change at any time so validation seems risky.

I also agree with your earlier point that the validation currently blocks the use of legitimate standardized keywords.  Case in point, I came to the repo tonight to file an issue to get *EncapOverhead added which is used in SDN environments and is a standardized key as defined by my team.

**Comment by PlagueHO** [comment]
Hi @dcuomo - that is some great info there and a pretty persuasive argument put forth to remove the validation. As we've also had not counter discussion put forth from the community it would seem pretty clear cut that we should eliminate the validation and just let people enter any value they wish.

We could provide a reference list in the README.MD for this resource but note that this won't be a complete list.

So I'll get onto making the change.
