### ISSUE TITLE
IPAddress - Default Gateway is not being set

### ISSUE THREAD

**Issue by PraveenKalavai** [PowerShell/NetworkingDsc#426]
IPAddress : Default Gateway is not being set during IP assignment

ResourceName: IPAddress

ISSUE DESCRIPTION : 
Can some one list out the order in which these resources have to be executed? when ever I try to  Assign IP address, it misses the default gateway and because of that the server gets disconnected from the domain. I'm having to login to the server and add the default gateway manually again.

    

#### Details of the scenario you tried and the problem that is occurring
I was trying to assign an additional static IP address.
The server already has default IP, default gateway and DNS Server details on it. I'm just trying to add a new static IP so I can bind it to my website in IIS later.
When I ran "Test-DscConfiguration" it says that the IP Address does NOT match desired state. 
But when I try to assign it, the resource is able to add an IP, but unable to add Default Gateway. It is causing the server to disconnect from the domain controller.

#### Verbose logs showing the problem
Failed to connect to the target machine to get the deployment status. More details: Connecting to remote server 'ServerName' failed with the following error message : WinRM cannot complete the operation. Verify that the specified computer name is valid, that the computer is accessible over the network, and that a firewall exception for the WinRM service is enabled and allows access from this computer. By default, the WinRM firewall exception for public profiles limits access to remote computers within the same local subnet. For more information, see the about_Remote_Troubleshooting Help topic.. Check the machine for deployment status.

#### Suggested solution to the issue
I'm not sure if I'm missing any other resources or a specific order to apply the configuration.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
param
(
        # Check/assign IPV4 Address
	[String] $InternetAlias = 'ProdNet',
	[String] $DefaultGateway = '10.114.66.1',
        [String] $IPAddress = '10.114.66.178/23'
	
)

Configuration IPAssignment
{
    #Import the module that defines custom resources
    Import-DscResource -Module NetworkingDsc

    Node LocalHost
    {
        # Disable DHCP 
	NetIPInterface DisableDhcp
        {
            InterfaceAlias = $InternetAlias
            AddressFamily  = 'IPv4'
            Dhcp           = 'Enabled'
        }
        # Add Default Gateway
	DefaultGatewayAddress SetDefaultGateway
        {
            Address        = $DefaultGateway
            InterfaceAlias = $InternetAlias
            AddressFamily  = 'IPv4'
        }
        # Check/Assign IPv4 Address
	IPAddress IPv4Assignment
	{
	    IPAddress      = $IPAddress
	    InterfaceAlias = $InternetAlias
	    AddressFamily  = 'IPV4'
	    KeepExistingAddress = $true
	}
    }
}


IPAssignment 
```

#### The operating system the target node is running
OS on the server : Win 16

#### Version and build of PowerShell the target node is running
5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
NetworkingDsc 7.4.0.0

**Comment by PlagueHO** [comment]
Hi @PraveenKalavai - I don't generally bother disabling DHCP because that is not required when you manually set the IP Address (it turns off DHCP anyway).

The following is what I use:
```powershell
Configuration Networking {
    Import-DscResource -ModuleName NetworkingDsc -ModuleVersion 7.4.0.0
    IPAddress IPv4_2 {
        InterfaceAlias = 'AADC Domain Private Site A'
        AddressFamily  = 'IPv4'
        IPAddress      = '192.168.128.10/24'
    }
    DefaultGatewayAddress IPv4G_2 {
        InterfaceAlias = 'AADC Domain Private Site A'
        AddressFamily  = 'IPv4'
        Address        = '192.168.128.19'
    }
    DnsServerAddress IPv4D_2 {
        InterfaceAlias = 'AADC Domain Private Site A'
        AddressFamily  = 'IPv4'
        Address        = '192.168.128.10'
    }
}
```

**Comment by PraveenKalavai** [comment]
@PlagueHO 

Thanks for the response.
Does it have to be executed in the same order as your configuration?
- IP address
- Default Gateway
- DNS Server Address

In my case, the server already has default IP, gateway and DNS Server address configured in the NIC.
All I'm trying to do was add a new static IP. So, shouldn't just the IPAddress resource work?
Do I have to also add default gateway and DNS Server addresses after the IP assignment even though they are already available?

I removed the NetIPInterface resource and just tried to add the IP with IPAddress resource. It still disconnected the server from the domain by removing the already available default gateway.

Thanks,
Praveen

**Comment by PlagueHO** [comment]
Hi @PraveenKalavai - oh I see, sorry, I didn't read your issue carefully.

The thing to remember with the IPAddress resource is that it will set the IP adressess to exactly what you specify in this resource and remove any ones not specified.

What you will need to do is specify the full list of IP Addresses you want the adapter to have in your resource. E.g.
```powershell
        IPAddress NewIPv4Address
        {
            IPAddress      = '192.168.10.5/24','192.168.10.6/24'
            InterfaceAlias = 'Ethernet'
            AddressFamily  = 'IPV4'
        }
```

Just specifying the one you want to add won't work because it will remove any others not specified. 
Does that make sense?

**Comment by PraveenKalavai** [comment]
Awesome!
So in addition to specifying the full list of IP addresses, I still need to have 'DefaultGatewayAddress' and 'DNSServerAddress' resources in my configuration, right?

or just IPAddress and DefaultGateway will suffice, since DNS Server Address is already configured?

**Comment by PlagueHO** [comment]
Hi @PraveenKalavai - just the IP Addresses and DefaultGatewayAddress should be fine since DNS is already configured.

But in general, the more you specify with DSC, the more your machine will always remain in a "known" state. So I tend to set everything (including DNS).

**Comment by PraveenKalavai** [comment]
> The thing to remember with the IPAddress resource is that it will set the IP adressess to exactly what you specify in this resource and remove any ones not specified.

I thought the property 'KeepExistingAddress' = $true will not delete existing IPs and will just add the new IP. May be that needs to be looked into!


![image](https://user-images.githubusercontent.com/36277675/67607719-75127180-f753-11e9-8ddc-b3adfdf676ef.png)

Specifying the full list of IP Addresses worked!!
Thank you!
The issue can now be closed 👍

**Comment by PlagueHO** [comment]
Pleasure to help @PraveenKalavai ! Thank you!

**Comment by PraveenKalavai** [comment]
@PlagueHO 
Just a small update.. I tried setting the property KeepExistingAddress = $true
It actually retained my existing IPs. 👍

**Comment by PlagueHO** [comment]
@PraveenKalavai - oh yes, you're right - that flag was added about 9 months ago to enable this behavior. I completely forgot.
